//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventario_productos_crub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Inventario
    {
        [Display(Name = "#")]
        public int InventarioID { get; set; }
        [Display(Name = "#")]
        public int ProductoID { get; set; }
        [Display(Name = "#")]
        public int Cantidad { get; set; }
        [Display(Name = "#")]
        public string Ubicacion { get; set; }
        public Nullable<System.DateTime> UltimaActualizacion { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
